# Generated by Django 4.2.4 on 2023-10-08 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='frenchise_register_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frenchise_name', models.CharField(max_length=30)),
                ('DOB', models.DateField(max_length=8, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('city', models.CharField(max_length=20, null=True)),
                ('Pin_code', models.PositiveIntegerField()),
                ('Work_Type', models.CharField(choices=[('Student', 'Student'), ('Driver', 'Driver'), ('Employee', 'Employee'), ('Shop owner', 'Shop owner'), ('Delivery boy', 'Delivery boy'), ('Other', 'Other')], max_length=20)),
                ('Address_Type', models.CharField(choices=[('Home with Family', 'Home with Family'), ('Rented with Family', 'Rented with Family'), ('Rented with Friends', 'Rented with Friends'), ('Hostel/PG', 'Hostel/PG')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
