# Generated by Django 4.2.4 on 2023-10-08 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frenchise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='frenchise_employee_register_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.PositiveIntegerField()),
                ('employee_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('frenchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
