# Generated by Django 4.2.4 on 2023-10-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frenchise', '0002_frenchise_employee_register_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frenchise_employee_register_model',
            old_name='frenchise',
            new_name='user',
        ),
    ]
