# Generated by Django 4.2.6 on 2023-10-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frenchise', '0004_profilefrenchise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefrenchise',
            name='Work_Type',
        ),
    ]
