# Generated by Django 4.2.6 on 2023-10-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frenchise', '0006_alter_profilefrenchise_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefrenchise',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profilefrenchise',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
    ]
