# Generated by Django 4.2.4 on 2023-10-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frenchise', '0008_employee_registration_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frenchise_employee_register_model',
            old_name='employee_name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='frenchise_employee_register_model',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='frenchise_employee_register_model',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='frenchise_employee_register_model',
            name='username',
            field=models.CharField(default='username', max_length=15),
        ),
        migrations.DeleteModel(
            name='employee_registration_model',
        ),
    ]
