# Generated by Django 4.2.6 on 2023-10-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frenchise', '0011_profilefrenchise_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefrenchise',
            name='Role',
            field=models.CharField(default='not specified', max_length=120),
        ),
    ]
