# Generated by Django 4.2.6 on 2023-10-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frenchise', '0012_alter_profilefrenchise_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='frenchise_employee_register_model',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
