# Generated by Django 4.2.6 on 2023-10-12 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('clientName', models.CharField(max_length=100)),
                ('PAN', models.CharField(max_length=16)),
                ('number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('clientName', models.CharField(max_length=100)),
                ('PAN', models.CharField(max_length=16)),
                ('number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
