# Generated by Django 4.2.4 on 2023-10-15 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companystaff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Active', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='loan',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Active', max_length=50, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Mutual_Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('clientName', models.CharField(max_length=100)),
                ('PAN', models.CharField(max_length=16)),
                ('number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Active', max_length=50, verbose_name='Status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Demat_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('clientName', models.CharField(max_length=100)),
                ('PAN', models.CharField(max_length=16)),
                ('number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Active', max_length=50, verbose_name='Status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
